# Generated by Django 2.2.6 on 2019-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=100)),
                ('clientAddress', models.CharField(max_length=100)),
                ('clientTelephone', models.CharField(max_length=100)),
                ('clientContact', models.CharField(max_length=100)),
                ('clientJobTitle', models.CharField(max_length=100)),
                ('skillRequired', models.TextField()),
                ('educationLevel', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('daysNeeded', models.IntegerField()),
                ('dailyHours', models.IntegerField()),
                ('dailyRate', models.FloatField()),
            ],
        ),
    ]
