# Generated by Django 2.2.6 on 2019-12-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='skillRequired',
            field=models.CharField(max_length=1000),
        ),
    ]
